### ISSUE TITLE
TransactionScope, Outbox, EF Core

### ISSUE THREAD

**Issue by Tobias-Gr** [Particular/NServiceBus.Persistence.Sql#124]
Hi,

my question relates to https://github.com/Particular/NServiceBus.Persistence.Sql/issues/2 but I want to be sure of not heading in a wrong direction.

Our scenario:
-SQL transport
-SQL persistence
-Business data via Entity Framework Core; EF Core uses session.Connection and session.Transaction as described here: https://docs.particular.net/samples/sqltransport-sqlpersistence/ 

Are following assumptions correct?
1) We do not need Outbox if we store everything in a single catalog and it is safe to ignore the AmbientTransactionWarning as described here: https://docs.particular.net/samples/sqltransport-sqlpersistence/
2) We need Outbox if we have multiple catalogs for queues and data as described here: https://docs.particular.net/samples/outbox/sqltransport-sqlpersistence-ef/

Thanks
Tobias

**Comment by SzymonPobiega** [comment]
1. In your case you can either ignore the warning (it is safe to ignore it because the consistency is guaranteed by means of handle it  being enlisted, EF does not have to handle it in any special way) or you can actually switch the transport to `SendsAtomicWithReceive` transaction mode. In this mode the SQL Server transport uses a ADO.NET transaction and passes it to the SQL Persistence. SQL Persistence on the other hand makes it available as `context.Transaction`. This is enough to keep you consistent. No outbox needed.
2. Short answer: Yes. Long answer: if you happen to have all NServiceBus-managed data in one catalog and in your handler you access data in another catalog it is OK to do so without the outbox. All you need to do is use catalog-qualified (three part) table names e.g. `MyBusinessData.dbo.MyTable` in the queries. NServiceBus is going to use the initial catalog as specified in the connection string. SQL Server supports transaction across multiple catalogs as long as they are in the same instance. Note it might be more complex in case of availability groups but I don't know enough to tell for sure.

**Comment by Tobias-Gr** [comment]
Hi Szymon,

thanks for the clarification.

Regarding 1):
Which transport configuration do you recommend? Is SendsAtomicWithReceive better (better performance?) for this scenario because SQL persistence in contrast to NHibernate does not need the TransactionScope?

Thanks
Tobias

**Comment by SzymonPobiega** [comment]
@Tobias-Gr the performance should be roughly the same as with a single SQL Server instance `TransactionScope` just wraps a single-phase transaction. The benefits of using `SendsAtomicWithReceive` are:
 * No need to mute a warning (and explain to other developers why we need to mute it)
 * No danger of accidentally enlisting other transactional resources

Let me elaborate on the second point. `TransactionScope` is a double-edged sword in my opinion. It allows you to easily declare transactions spanning multiple resources. The downside is the implicit nature of it. Anything and everything can enlist in that transaction. Let me give you an example.

Somebody on your team creates a handler that queries some other database. It does not update any information, only load some reference data. If you had a transaction scope present, opening that connection would force the transaction to be promoted. Now, depending on the environment, it would either:
 * Silently promote the transaction to a distributed one. Assuming DTC is configured, your throughput would suffer because now suddenly all you local fast transaction go through DTC
 * Fail because there is no DTC configured
What's even worse, the outcome would depend on the environment. On your local machine it is likely that you have DTC running so all the tests would pass. You might get a nasty surprise on production when you see all your messages going through FLR, SLR and eventually ending up in the error queue.

**Comment by Tobias-Gr** [comment]
Thanks!
