### ISSUE TITLE
Saga Finder

### ISSUE THREAD

**Issue by Tobias-Gr** [Particular/NServiceBus.Persistence.Sql#131]
Hi,
the examples for saga finders use JSON_VALUE and need SQL Server 2016 to work.

https://docs.particular.net/samples/saga/sql-sagafinder/#saga-finders
https://docs.particular.net/persistence/sql/saga

Is there any possibility to achieve the same with SQL Server 2014?

Thanks!
Tobias

**Comment by DavidBoike** [comment]
Hi @Tobias-Gr,

I don't really think there is a way to do that, since (as you mentioned) JSON_VALUE only appears in 2016. We perhaps should do a better job of making that clear in the documentation though.

That said, I have always considered saga finders as a bit of an odd, curious feature, and have never had a need to implement one in real life. I always struggle with why we support it in the first place. Could you explain your business case for a custom saga finder? Maybe we can suggest an alternative.

**Comment by Tobias-Gr** [comment]
Hi @DavidBoike,

thanks! Making the docs clearer is a good idea.

Our need for saga finders is more theoretical as yet but our idea is the same as in the sample (https://docs.particular.net/samples/saga/sql-sagafinder/#saga-finders): Being able to map to a saga by more than one correlation id in order to keep (otherwise unnecessary) ids out of our messages.

What is your point of view on this?

**Comment by DavidBoike** [comment]
I raised https://github.com/Particular/docs.particular.net/pull/2989 to amend our docs.

In the past I have created a "composite key" that becomes the saga key and is passed around with every message as an implementation detail. The strongest candidates for saga finders are (in my opinion) where you have messages coming from an external partner whom you can't convince to include that composite key, and it's not possible (for whatever reason) for an anti-corruption layer to add it into the mix.

But, supporting saga finders in SQL Persistence on SQL Server is very much technically limited by the JSON_VALUE function, so there's no way to implement before SQL 2016.

**Comment by weralabaj** [comment]
@Tobias-Gr I believe that @DavidBoike 's answer should provide some clarification regarding saga finders, so I'll close the issue. If you feel that there's more to discuss or want to follow up, please, reopen this issue.

Regards,
Weronika
