### ISSUE TITLE
SqlPersistence task fails when SagaData and Saga is not in the same assembly

### ISSUE THREAD

**Issue by jbakholt** [Particular/NServiceBus.Persistence.Sql#222]
Error example:
SqlPersistenceTask: Error in 'OrderSaga'. Error:The type 'OrderSaga' uses a SagaData type 'OrderSagaData' that is not defined in the same assembly.

Is this restriction by design?

**Comment by weralabaj** [comment]
Hi @jbakholt!

Indeed, the restriction is by design. Typically the saga data is defined in the same assembly, often as a nested class even. Generally, we don't recommend re-using saga data definitions across multiple sagas.

That assumption allows us to make some performance optimizations, e.g. we don't have to scan other assemblies at compile time.

The exception message or some kind of verification would be better though. Also, I'm not sure (I'll verify) if those recommendations are explicitly stated in the documentation. Would a better exception and clear guideline solve the problem here? Or is there some requirement for you to have those two things separated?

**Comment by jbakholt** [comment]
The reason for separating the Saga data from the saga is a matter of convenience. We are considering building a Saga data storage for querying purposes. To make that happen our sagas will have to send a copy of the it self to the saga query storage using messaging/NSB off course. 

We could of course define an exact copy of the saga data in a separate assembly and use that for transporting the sagadata but as a short cut it would be nice to be able to reuse the saga data definition without having to reference the saga assembly outside the saga itself. I hope it makes sense.

**Comment by weralabaj** [comment]
Hm... Generally, we [don't recommend querying saga data](https://docs.particular.net/nservicebus/sagas/#querying-saga-data) and there are various ways that can be avoided that we could suggest. There may be valid reasons to break that rule, of course, but I think it'd be good to discuss your business scenario in a more depth with one of our solution architects because that seems to be an exceptional situation.
 
If nothing else, at least you'll ensure you're on the right path and we'll get some new insights into usage scenarios. If that sounds good, please email me at weronika.labaj at particular.net and I'll make sure somebody gets in touch with you to discuss, OK?

**Comment by jbakholt** [comment]
Thanks for sharing the link. 

For the same reasons we are not planning to query the saga data directly. By having the sagas publish a "copy" of the saga data as an event when the saga is created or modified to a separate saga query storage with a layout more suitable for querying  we avoid the most glaring pitfalls I think.

Per your recommendation : "The recommended approach is for the saga to publish events, containing the required data, and have handlers that process these events and store the data in one or more read model(s) for querying purposes"

So it really comes down to being able reuse the saga data definitions by keeping them en a "shared" asssembly.  

Would you consider making it optional where to define the saga data and thus let it be up to the developer to make the decision whether to sacrifice performance for reuse-ability.

**Comment by dvdstelt** [comment]
> So it really comes down to being able reuse the saga data definitions by keeping them in a "shared" assembly.

Would that not mean you'd be publishing the saga data and thus have a single class implement both IContainSagaData and IEvent? Obviously you can use conventions, but that doesn't change a thing of the intent of what I'm saying and what one would try to achieve with that method.

A Saga and its state are so tightly bound together that usually the state is a nested class inside the class implementing the saga.

If you would need to publish _all this data_ inside an event I would still recommend to create a new message class. That way you can represent the intent much better with the name of that class. Copying all the properties should be very cheap, as it only holds only data to orchestrate the business process. And if there are several properties, you can always use AutoMapper. But if you have that many properties, it's likely this is already a sign that the design isn't correct.

**Comment by danielmarbach** [comment]
@jbakholt when it comes to sagas and message contracts I strongly recommend you to put away the developer mindset of "Don't repeat yourself" and "reusability". A saga defines a business process with its behaviour and data. A business process is unique to the service it belongs to as well as the shape of the data that it gathers. When two business processes have the same N properties that does not matter at all. Those two processes still need to be individually evolvable both in terms of behaviour and data. By trying to put the SOLID and DRY principles on top of that you are essentially creating unnecessary coupling for no added value. If it looks like a duck and quacks like a duck it doesn't necessarily have to be a duck. It could be me trying out my latest carnival costume ;)

![image](https://user-images.githubusercontent.com/174258/32657456-1a42f98e-c616-11e7-9471-fd3feca4437f.png)

Copyright of the picture belongs to https://www.aliexpress.com/item/No-1-MASCOT-yellow-duck-mascot-costume-custom-fancy-costume-anime-cosplay-kits-mascotte-theme-fancy/1725376542.html

**Comment by weralabaj** [comment]
@jbakholt I asked around and as you see above, as a company we have a strong belief that this technical change should not be necessary ;) But it's really hard to discuss abstract principles, much better to focus on specific scenarios and business use-cases you have and possible alternatives.

That's why I suggested a video-call. Please, consider it, it's free of charge and I think both sides will benefit. It could be a conversation with just you or also other people from your team, if necessary, there may be more than one call.

Maybe there's a gap in our reasoning, but I was told that this particular decision was heavily discussed internally, so instead of rushing to make changes I want to ensure we really understand what you're trying to do.

**Comment by jbakholt** [comment]
@dvdstelt @danielmarbach My bad. I failed to mention that we have no intention of storing the internal saga data structures, headers, timeouts or anything else that is related to the saga or saga state in the saga data query storage. On arrival to the query storage we will cherry pick the domain model objects that is defined in the saga data object.

I do agree that publishing the saga data structure as a whole will introduce unwanted tight coupling and violate the single responsibility principle. I can see that now. So I agree that i'm better of defining data contracts for the sole purpose of transporting the needed data from the saga to the saga query storage and use automapper to do the heavy lifting in both ends.

@weralabaj no need to setup a meeting. Your colleagues has convinced me that I was taking the wrong path.

**Comment by weralabaj** [comment]
Happy we could help, let me/us know if anything else comes up. Also, the [community forum](https://discuss.particular.net/) is a place where we have a lot of discussions around design, etc. It's a new space, so not much history there yet, but that is a good place to talk to other NSB users.

**Comment by jbakholt** [comment]
@danielmarbach nice suit btw ;o)
