### ISSUE TITLE
Installer support for multi hosting

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.Persistence.Sql#248]
when multi-hosting the installers will incorrectly run all sql installation scripts for all endpoints on every endpoint. 

needs a way of producing and executing scripts in some kind of convention so as to only run the scripts for a specific endpoint

**Comment by SzymonPobiega** [comment]
@SimonCropp you mean when multiple endpoints are started in a single process?

**Comment by SimonCropp** [comment]
Yep

**Comment by SzymonPobiega** [comment]
@SimonCropp but the scripts are endpoint-neutral? Do you mean specifically saga scripts?

**Comment by SzymonPobiega** [comment]
@Particular/sqlpersistence-maintainers frankly I have no idea who can we solve this. Since the endpoint name is not known at compile time we can't really use it in the names of the scripts or their folders.

@SimonCropp do I understand correctly that the scenario is one dll/exe which creates multiple endpoints? Can you post a repro?

**Comment by DavidBoike** [comment]
Are the installers just blindly executing every file they find with their own endpoint name? If so it might be adequate just to have each endpoint take better stock of what they should be installing (what features are active & what saga types do I have loaded) and then only execute those.

**Comment by SimonCropp** [comment]
> Are the installers just blindly executing every file they find with their own endpoint name

yes

any update on this?

**Comment by SzymonPobiega** [comment]
@SimonCropp nope, no progress. I don't have any ideas how this could be implemented given the fact that the endpoint name is not known when the scripts are generated.

**Comment by DavidBoike** [comment]
Ok, so my idea on this is that we don't need to do anything different when the scripts are generated. Generate everything - you're going to need it.

In the installers, however, we need to have the installers dependent upon all the features that set up everything. At that point, we should be able to tell that the SqlP timeout persister is activated (execute that script) and Outbox is not (don't execute that one), and then enumerate through the sagas in the loaded types we have, and execute each one of those.

@SzymonPobiega think that could work?

**Comment by SzymonPobiega** [comment]
@DavidBoike I think the sagas would be the problem because it would be hard to tell which sagas should be deployed to which endpoint's DBs. 

That said, @andreasohlund had an idea to generate the scripts in a folder named after the VS project. Then we can map endpoints to projects if there is more than one.
