### ISSUE TITLE
is the System.Data.SqlClient nuget ref redundant for net452?

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.Persistence.Sql#273]

**Comment by bording** [comment]
No, the package reference is not redundant because we target both `netstandard2.0` and  `net452`.

Given the following scenario:

- A class library targets `netstandard2.0` and takes a dependency on NServiceBus.Persistence.Sql
- That class library is referenced from from an app that targets `net461` or higher (something that supports `netstandard2.0`)
- NServiceBus.Persistence.Sql is not directly referenced by the app, but is only referenced transitively through the class library

If the class library uses a `System.Data.SqlClient` type, for example, it calls the the persistence's `ConnectionBuilder` API, then the app will throw at runtime if we didn't reference `System.Data.SqlClient` for `net452` as well `netstandard2.0`. The shim version of the assembly is needed to ensure the types are properly forwarded.

Because of these kinds of issues, conditional dependencies in general are something to avoid.

**Comment by SimonCropp** [comment]
Fair enough
