### ISSUE TITLE
Allow SQL persistence to use different connection strings for subscriptions and timeouts

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus.Persistence.Sql#276]
Update: [Here](https://gist.github.com/SzymonPobiega/49e3d1b340755dee8edbfb2dc93725c1) the code to smoke test this feature as it is super hard to test it automatically (requires separate DBs etc.)

Allow SQL persistence to use different data stores for different persistence concerns e.g. different database for subscriptions and for sagas.

New API proposal:

```
//Current API
var persistence = config.UsePersistence<SqlPersistence>();
persistence.ConnectionBuilder(() => new SqlConnection())

//New API
var persistence = config.UsePersistence<SqlPersistence>();
var subscriptions = persistence.SubscriptionSettings();
subscriptions.ConnectionBuilder(() => new SqlConnection())

var timeouts = persistence.TimeoutSettings();
timeouts.ConnectionBuilder(() => new SqlConnection())

Customer-provided implementation is here: https://github.com/Particular/NServiceBus.Persistence.Sql/pull/267

**Comment by SzymonPobiega** [comment]
@Particular/sqlpersistence-maintainers I propose this to be part of the next maintenance release

**Comment by SzymonPobiega** [comment]
@DavidBoike @weralabaj @tmasternak can you review the API I proposed? I hope it covers the saga/outbox relation well enough. The rules here are a bit tricky:
 * When the outbox is enabled, the outbox connection is used for sagas so sagas can't specify their connection explicitly. If you want to customize where the sagas are stored, you customize the *outbox* connection factory
 * When the outbox is disabled and you want to customize where the sagas are stored, you customize the *sagas* connection factory
 * When the outbox is disable you can also use a connection factory that takes the message context so that you can store your sagas based on the message headers

I could not find a way to express these rules in a type-safe manner. I think throwing an exception if someone provides a saga connection when the outbox is enabled is a good enough solution.

**Comment by weralabaj** [comment]
Also 👍 for illegal configuration, although I have a bit of a challenge to understand what scenarios we're covering and why.

I get the argument about storing all subscriptions in a single database, but I'm not sure why sagas would be stored in various databases?

Is it still a valid scenario since we moved away from a multi-database setup in SQL transport?

**Comment by tmasternak** [comment]
> Is it still a valid scenario since we moved away from a multi-database setup in SQL transport?

I think what we want to tackle is:
 * single db for messaging,
 * per-tenant db for saga data.

**Comment by SzymonPobiega** [comment]
After a call with the customer we de-scoped separate connections for timeouts and saga/outbox leaving only the subscriptions in scope.

**Comment by markgould** [comment]
Does it make sense to only have the dialect at a global level? We use it to specify a schema. Right now (it appears) you would need to use the same schema name for saga/subscription/timeouts.

In our business database we use the schema nsb for our saga, timeout and (until now) subscription data. In our queue database we haven't been using a schema (just default dbo). Not a huge issue if we have to adopt the same schema in our queue db just for subscriptions, just something that might be worth thinking about.

**Comment by weralabaj** [comment]
@markgould We'll discuss this in more detail internally, that feature has been added to get a customer unstuck, so it's not fully fleshed out yet.

I'm not completely sure that I understand your scenario though, do you want to use various schemas per persistence concern (i.e. timeouts, sagas and subscriptions) or is this about using one schema for transport (SQL Server) and another for all persistence concerns (SQL persistence)? The first one is not possible at the moment, however, the latter should work I think. Can you provide a bit more detail?

**Comment by markgould** [comment]
I can explain a little further. Until now we have been using one database purely for transport and one database for the business data and SQL persistence. 

Since transport is only used for NSB queues, we haven't bothered with a custom schema, so it looks like this:

- dbo.audit
- dbo.error
- dbo.EndpointName
- dbo.EndPointName.Retries

etc.

For our business database, we do a lot of database deployments and we do not deploy any of the NSB infrastructure tables, those are handled using the generated scripts, so we keep NSB related items in a nsb schema, so an example would be this:

- dbo.Customer
- dbo.Payment
- nsb.EndPointName_TimeoutData
- nsb.EndPointName_SubscriptionData

For this reason, https://github.com/Particular/NServiceBus.SqlServer/issues/438 we decided to move the subscription data to the transport database. 

Now our transport database looks like this:

- dbo.audit
- dbo.error
- dbo.EndpointName
- dbo.EndPointName.Retries
- nsb.EndPointName_SubscriptionData

It isn't the end of the world, we will just have to create the nsb schema in all of our transport databases (we are an ISV). We could change the transport to use the nsb schema too but that might be more effort than it is worth.

**Comment by weralabaj** [comment]
Ah... Now I get you, so you'll need to somehow ensure that this schema actually exists by either creating it manually or using scripts? In that case I agree, just creating those schemas will be probably the easiest/fastest way to get unstuck.

However, if you had some time it'd be great if we could discuss your system design in a bit more detail to understand what scenarios we should support to make your life easier going forward. I'll email you directly to discuss this.

**Comment by SzymonPobiega** [comment]
Closed via https://github.com/Particular/NServiceBus.Persistence.Sql/pull/284

**Comment by indualagarsamy** [comment]
@Particular/keeping-the-lights-on-squad - this issue has the label "Candidate for next release", however it appears that it was already part of 4.1.1 milestone. Can you clear the labels for the issue?
