### ISSUE TITLE
Register Synchronized Storage Session in the Dependency Injection container

### ISSUE THREAD

**Issue by Thorarin** [Particular/NServiceBus.Persistence.Sql#375]
I've been trying to use SQL persistence and outbox in an existing project, without having to change too much code. One thing I would like to do is to reuse a `SqlConnection` for both the Outbox feature, as well as for dependencies registered in the child container that is created for the incoming message pipeline. 

```csharp
// Instead of writing this:
persistence.ConnectionBuilder(() => new SqlConnection("connection string");

// I would like to do this:
persistence.ConnectionBuilder((IBuilder builder) => builder.Build<SqlConnection>();
```

Right now, if I want to use the same `SqlConnection` for my message pipeline **and** resolving dependencies (like an EF DbContext), I can only do that by using `context.SynchronizedStorageSession.SqlPersistenceSession().Connection` in my message handler, obtaining the existing connection, and then create another child of the child container where I register that connection somehow. **I end up with quite a bit of boiler plate infrastructure code in my message handlers.**

With the method above, I would be able to use constructor injection directly on the message handler. Unfortunately it's exceedingly difficult to achieve this as things are now. `IConnectionManager` is internal, and even if it weren't, I don't see a way I would be able to access the `RootContext` or something that gives me access to the child container. I guess that `RootContext` would have to be part of the `IConnectionManager.Build(...)` method signature.

I've managed a workaround using by combining a callback when the child container gets built, `AsyncLocal<T>` and a service locator pattern inside my ConnectionBuilder Func, but needless to say it's not looking pretty.

**Comment by SzymonPobiega** [comment]
@Thorarin 

The fact that the Outbox correctness depends on the ability of NServiceBus to manage the connection forced us to design the connection APIs in such a way that it is intentionally difficult to provide your own connection to the Outbox. NServiceBus needs to fully control it.

The approach for dealing with EF integration is to pass the NServiceBus-managed connection to EF, not vice versa. The simplest way of doing this is creating the EF context in the `Handle` method and using the connection/transaction objects obtained from `IMessageHandlingObject`. This approach is documented [here](https://docs.particular.net/persistence/sql/accessing-data#using-in-a-handler).

It might be cumbersome with large number of handlers. In that case it might be desirable to inject your EF contexts into the handlers. In that case you need an additional object in the container that holds your connection and transaction. When registering your EF contexts in the container, you use a factory method like this pseudocode

`myContainer.Register<MyContext>(container => {
   var connectionHolder = container.Build<ConnectionHolder>();
   return new MyContext(connectionHolder.Connection, connectionHolder.Transaction);
});

the `ConnectionHolder` is a single class with two properties. It has to be registered in NSB container in `UnitOfWork` scope so that a new instance is created for each message being handled. Last but not least, you need a [behavior](https://docs.particular.net/nservicebus/pipeline/manipulate-with-behaviors) in the `IInvokeHandlerContext` that resolves `ConnectionHolder` from the container and sets is connection and transaction properties.

This approach benefits from the fact that the handlers are resolved after your behavior sets the properties of the connection holder.

**Comment by Thorarin** [comment]
@SzymonPobiega I ended up with a similar approach after noticing issues with the method I described in the original issue.

Before all this I started with your described behavior-based approach, but unlike what you suggest, the values were being set in my `ConnectionHolder` too late. In my message handler constructor, the holder was empty, by the time `Handle` was called, they are filled. Alas, too late for regular constructor injection. This is consistent with what appears to happen in the [`LoadHandlersConnector`](https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Pipeline/Incoming/LoadHandlersConnector.cs) code though: the `SynchronizedStorageSession` is constructed, then the next order of business is instantiating the handlers.

The only way I could get it to work without replacing the stage connector, was to intercept calls to `ISynchronizedStorageAdapter` and `ISynchronizedStorage` and intialize my `ConnectionHolder` from there. Instead of duplicating relatively complex code, that meant adding some "simple" code.

**Comment by SzymonPobiega** [comment]
@Thorarin our Developer Experience department is going to look at this soon. I agree with you that it should be much easier to this thing up. Injecting `DataContext`s or repositories is a very common use case. 

I didn't notice that the handler is created before the invoke handler pipeline is invoked. My bad. Before this scenario is properly addressed you can try adding a dummy handler of `IMessage` that is always [executed first](https://docs.particular.net/nservicebus/handlers/handler-ordering). This dummy handler will ensure that the behavior in `IInvokeHandlerContext` has been called before the first "production" handler is invoked.

Another approach might be using `Lazy<T>`, provided your container supports them. If a handler constructor had `Lazy<MyDataContext>` as an argument then it would only be resolved when the handler is actually executed so the behavior would already set the connection and transaction.

**Comment by arodus** [comment]
@Thorarin I'm facing the exact same issue. Would you mind sharing how you intercepted the calls to `ISynchronizedStorageAdapter` and `ISynchronizedStorage` to make constructor inejction working?
