### ISSUE TITLE
Allow to specify transaction Isolation level

### ISSUE THREAD

**Issue by ericvan76** [Particular/NServiceBus.Persistence.Sql#525]
When using Sql Persistence with Outbox, the business data saving requires higher transaction isolation level. e.g RepeatableRead. But currently the SynchronizedStorage BeginTransaction with Unspecified isolation level.

see ref:
https://github.com/Particular/NServiceBus.Persistence.Sql/blob/26bfe625594a83dc855e15b7212b51382edf72a3/src/SqlPersistence/SynchronizedStorage/SynchronizedStorage.cs#L21

**Comment by SzymonPobiega** [comment]
Hi @ericvan76 . We don't support setting the isolation level directly but you might try using [TransactionScope mode](https://docs.particular.net/persistence/sql/outbox#transaction-type-transaction-scope) we recently added to SQL Persistence Outbox. In this mode the outbox uses the `TransactionScope` instead of ADO.NET transaction and the default isolation level of `TransactionScope` is `Serializable`. So if you don't mind having even higher (than `RepeatableRead`) isolation level, that should help you.

In the meantime we will add your request to the backlog of enhancements for SQL Persistence. Thanks for raising this.

**Comment by ericvan76** [comment]
Hi @SzymonPobiega Thanks for the suggestion. Currently, I made a workaround to ensure repeatable read in the business logic. `TransactionScope` is something we're trying to avoid at the moment unless there is a specific need. The reason behind is that the ef-core doesn't support distributed transaction yet, which means multiple db contexts need to share the SqlConnection, then `TransactionScope` seems useless in my scenario.

Thank you for the backlog anyway.

**Comment by SzymonPobiega** [comment]
@ericvan76 this has been merged and will be released soon in 6.1
