### ISSUE TITLE
Outbox tables grows indefinitely

### ISSUE THREAD

**Issue by pardahlman** [Particular/NServiceBus.Persistence.Sql#575]
Because of a heuristic built into SQL Server, outbox records of size between 4 KB and 8 KB (which corresponds to outgoing messages between 1.5K and 3K characters long, including headers) were stored in a very inefficient manner -- one record (~120 bytes long after the messages are dispatched) per page (8 KB). This resulted in 1.5% storage space utilization.

The fix adds a padding (whitespace) at the end of the JSON-serialized outgoing messages to ensure the row size is always either below 4 KB or above 8 KB.

<details>

We are using the outbox feature with MSSQL as underlying persistence. A while ago, we noticed that the outbox tables allocated a significant amount of disk. The largest table contained 12 000 000 records and used 80 GB (!). This was for one of many endpoints in our system.

When looking closer at [the SQL script used to create the outbox](https://github.com/Particular/NServiceBus.Persistence.Sql/blob/master/src/ScriptBuilder/Outbox/Create_MsSqlServer.sql), it came to our attention that the outbox tables does not have a clustered index, and is therefore a [heap](https://docs.microsoft.com/en-us/sql/relational-databases/indexes/heaps-tables-without-clustered-indexes?view=sql-server-ver15). Heaps differs from tables with a clustered indexes in a few ways, most notably: it needs to be rebuilt to reclaim wasted space.

Rebuilding the tables had the desired effect: a table that allocated 50GB decreased its disk usage to 130MB.

Microsoft documentation also states the following:

> Do not use a heap if the data is frequently updated. If you update a record and the update uses more space in the data pages than they are currently using, the record has to be moved to a data page that has enough free space. This creates a forwarded record pointing to the new location of the data, and forwarding pointer has to be written in the page that held that data previously, to indicate the new physical location. This introduces fragmentation in the heap. When scanning a heap, these pointers must be followed which limits read-ahead performance, and can incur additional I/O which reduces scan performance.

Without knowing the internals of NServiceBus I can assume that there are a few updates per records when processing messages.

With that in mind, I have the following questions:

1. Why is the table designed this way?
2. What is the recommended way of maintaining the outbox tables?

I have read all available documentation on the outbox and SQL storage but haven't found anything on this topic. Feel free to point me to the right direction or add relevant documentation.
</details>

**Comment by andreasohlund** [comment]
Given that the table is increasing in size it seems like the cleanup isn't running?

Have you disabled it? https://docs.particular.net/persistence/sql/outbox#deduplication-record-lifespan

**Comment by pardahlman** [comment]
We use the default cleanup settings with seven days retention, run every minute. 12 000 000 is the number of messages handled for this endpoint during this period of time.

**Comment by andreasohlund** [comment]
Ah, got it.

So you're asking if you should add any index to the table to make the cleanup more efficient? (are you having perf issues currently)

**Comment by akselsson** [comment]
Hi Andreas,
Our issue is that the outbox table has grown substantially in size due to fragmentation, which seem to be common among heaps. This leads to higher disk and cpu usage than we're comfortable with.

What would be the implications of switching to a clustered index for the outbox tables? Did you run any benchmarks on clustered tables versus heaps when you developed the outbox feature that made you choose heap storage?

**Comment by andreasohlund** [comment]
We have no benchmarks atm but I'm discussing this internally.

When you say clustered index do you means creating a new one or making the `Index_DispatchedAt` index the clustered one? https://docs.particular.net/persistence/sql/sqlserver-scripts#build-time-outbox-create-table

**Comment by DavidBoike** [comment]
The change to nonclustered was a conscious choice but apparently only solves half the problem. It was originally clustered in 1.0.0 but was switched in https://github.com/Particular/NServiceBus.Persistence.Sql/pull/33 because with the MessageId column being the primary key and MessageIds being basically guids, having it as a clustered index would mean the real data for the table on disk would have to be written in order of the (randomized) MessageId, leading to index fragmentation problems and SQL constantly reshuffling data between pages.

See the [upgrade guide from that release](https://docs.particular.net/persistence/upgrades/sql-1.0.0-1.0.1) or the [original PR](https://github.com/Particular/NServiceBus.Persistence.Sql/pull/10) (which was replaced by #33) for more details.

We should investigate this more thoroughly. My first thought is that we should act like SQL Transport and create a clustered index on a `RowVersion bigint IDENTITY(1,1) NOT NULL` column, but then I look at SQL Transport code and see conflicting results:

* SqlConstants.cs, which I think is the source of queue creation, [has the index but it's non-clustered](https://github.com/Particular/NServiceBus.SqlServer/blob/master/src/NServiceBus.Transport.SqlServer/Queuing/SqlConstants.cs#L166-L180).
* [This script](https://github.com/Particular/NServiceBus.SqlServer/blob/master/src/Scripts/Create-Databases.sql#L27-L41) - not sure what it's used for - creates an error queue with a clustered index.

**Comment by DavidBoike** [comment]
@akselsson after re-reading the [article you mentioned](https://docs.microsoft.com/en-us/sql/relational-databases/indexes/heaps-tables-without-clustered-indexes?view=sql-server-ver15) I'm less inclined to agree that storing in a heap in this circumstance is bad. The part you quoted in particular talks about when the data is frequently updated. Outbox data is not. The **outbox table** is updated frequently, sure, but an **outbox record** is updated precisely once, when the transport operations are dispatched, and always to a smaller size, because the outgoing transport operations (which may be quite big) are updated to be empty `[]`.

My recommendation to you right now would be to include Outbox tables in regularly scheduled database maintenance that includes running ALTER TABLE…REBUILD.

Long term we still need to investigate if we can optimize this by including a RowVersion or similar as I mentioned in the previous comment.

**Comment by akselsson** [comment]
Hi @DavidBoike 
I agree that our experience is conflicting with what's expected when I read the documentation. We'll try rebuilding outbox tables to see if it helps and hope that it won't create a big table lock during the rebuild phase.

The RowVersion route sounds promising. We look forward to hearing the results of that investigation. If that doesn't work, then perhaps you could look into letting applications provide a message id. That way we could try with incrementing uuid's and a clustered index on MessageId.

**Comment by SzymonPobiega** [comment]
@pardahlman we have fixed this in 6.1 and we are going to release the package soon. I moved your initial issue description to the `details` section and include the solution details at the top. Hope you don't mind.
