### ISSUE TITLE
change connection scoping when using a TransactionScope

### ISSUE THREAD

**Issue by SimonCropp** [Particular/NServiceBus.Persistence.Sql#594]
currently the sql persistence creates a sql connection+transaction, then those span the unit of work.

This makes this issue more likely to occur https://discuss.particular.net/t/this-platform-does-not-support-distributed-transactions/1807/3
```
using (var conn = OpenConnection("DB2"))
using (var conn = OpenConnection("DB3"))
{
   //Do work in DB 2
   //Do work in DB 3
}

even if both connection string are identical you will get a DTC escalation.
```

given when there is a TransactionScope, there is no need to have spanning sql connections+transactions. Instead the open+read and the save+end of sagas can happen against different distinct sql connections.

cc @SzymonPobiega

**Comment by SzymonPobiega** [comment]
Hey @SimonCropp 

I looked at it and it would break the assumption that you can access always the synchronized storage session in your handlers unless we create a connection per handler within that distributed transaction. Currently it is done before the `InvokeHandlers` stage of the pipeline. As a result, if you have a behavior in that stage that opens a connection, it will throw. 

If we moved the opening/closing of the connection to "just before handler" that would allow you to open and close your connections in that stage and still participate in the distributed transaction.

Before we further triage this one, can you check if you have any custom behavior in that stage? Any custom behaviors before that stage should be fine. 

Also, you can't have any custom behaviors that open connection in the outgoing pipeline before the fork that is responsible for batching because these stages are invoked while the handler executes.

**Comment by SzymonPobiega** [comment]
@SimonCropp I raised https://github.com/Particular/NServiceBus.Persistence.Sql/issues/645 to track the potential improvement related to late opening of SQL Server connection. I think we can close this one. Feel free to re-open if we missed some angle of the problem.

**Comment by SimonCropp** [comment]
@SzymonPobiega thanks
