### ISSUE TITLE
Outbox cleanup query uses unbounded DELETE

### ISSUE THREAD

**Issue by MarcinHoppe** [Particular/NServiceBus.Persistence.Sql#8]
Currently the Outbox cleaner deletes all the dispatched Outbox records using a single query, regardless of how many records there are. For endpoints with heavy traffic (a lot of new records inserted in a short period of time) this will lead to excessive locking (page locks) and finally to deadlocks and endpoint shutdowns.

Removing many records in one transaction is also quite a heavy operation for the transaction log.

The suggested solution is to use a loop with batched deletes (each in a separate transaction), very much like here:

https://github.com/Particular/NServiceBus.SqlServer/blob/develop/src/NServiceBus.SqlServer/Receiving/ExpiredMessagesPurger.cs#L35-L41

**Comment by SimonCropp** [comment]
@MarcinHoppe r u up for submitting a PR?

**Comment by MarcinHoppe** [comment]
@SimonCropp Possibly, maybe 😄.

Joking aside, I will submit a PR.

**Comment by SzymonPobiega** [comment]
@SimonCropp after discussion with @MarcinHoppe there are three alternatives that are more "breaking" and can be considered for 2.0

 1. Use a fixed-size (defined in config) outbox like a hashtable. We would hash the incoming message id to get the bucket in the fixed-size outbox. If the record is taken (Dispatched=false) we retry. If it is not taken, we use it. This way we never ever delete from the outbox.

2. Use double tables (green-blue?). We use green one until certain number of records is there. Then we switch to the blue one. Once we switch, we `truncate` the green table. In order to ensure we don't lose any data we would have to store durable what is the current table and each outbox insert would have to contain `WHERE` that ensures we're inserting to the right table

3. Use partitioning

**Comment by SimonCropp** [comment]
@MarcinHoppe any chance of getting that PR?

**Comment by MarcinHoppe** [comment]
@SimonCropp Not on my prio list at the moment. I assigned this to myself not to loose track of it.

**Comment by SimonCropp** [comment]
No worries. If someone else gets to it we will ping u for a review

**Comment by SimonCropp** [comment]
@MarcinHoppe https://github.com/Particular/NServiceBus.Persistence.Sql/issues/51

**Comment by MarcinHoppe** [comment]
I only had a look now, but looks good.
