### ISSUE TITLE
Saga sql scripts are not created if concrete saga inherits from abstract base saga class

### ISSUE THREAD

**Issue by StefanoVuerich** [Particular/NServiceBus.Persistence.Sql#830]
Hi,

I got a base class like this

``` C#
public abstract class AbstractBaseSaga<T> : Saga<T> where T : ContainsSagaData, new() 
{
  //implementation here
}
```

Concrete saga is inheriting from AbstractBaseSaga

``` C#
public class MyWorkflow : Saga<MySagaData>,
        IAmStartedByEvent<SagaStarted>,
        IHandleEvent<FirstCommandExecuted>,
        IHandleEvent<SecondCommandExecuted>,
        IHandleEvent<FinalCommandExecuted>
{
  //implementation here
}
```

In this case saga sql persistence folder in not created.

If MyWorkflow  inherits directly from Saga the folder is correctly created.

Do we have any restriction on inheritance?

thank you

**Comment by DavidBoike** [comment]
Hi @StefanoVuerich, that's correct. You can't have an abstract base class in your Saga inheritance chain.

This is because Sql Persistence is generating those scripts at compile time at the IL level, where you can't do full type reflection or follow an inheritance chain all the way back to System.Object. We have to look at all types and all we have to go on to decide if the class being looked at IS a saga at all is the name of the base type.

I'm guessing you had the AbstractBaseSaga in a separate project that did not reference NServiceBus.Persistence.Sql, otherwise you should have gotten a build error either that a saga type can't be abstract or that it cannot contain generic parameters. But because your project containing the abstract class did not reference the SQL package, the MSBuild task didn't run on it at all.

I'd like to know what you're trying to gain from an abstract base class in the first place, as it's not evident from the snippets you've shared above. We haven't seen a lot of concrete use cases for doing this, and having a few would help us to evolve this behavior in future versions. I also might be able to suggest an alternate method.

**Comment by StefanoVuerich** [comment]
Hi @DavidBoike.

You are correct, AbstractBaseSaga is in a separate project and it takes a generic type as saga  data parameter.
If I reference NServiceBus.Persistence.Sql I got compile **SqlPersistenceTask: The type 'IRS.Framework.Workflow.AbstractBaseSaga `1' has generic parameters**.

In the AbstractBaseSaga  we define:
- a common ConfigureHowToFindSaga, which is using reflection to automatically map, start end handled event
- wrapper send command method which includes logging logic
- wrapped publish event method which includes logging logic

In version 5 of NServiceBus this was working.

Are you able to suggest an alternate method?

Best regards

**Comment by DavidBoike** [comment]
You must have been using a different persistence in NServiceBus 5, since SQL Persistence was not released until NServiceBus 6.

The reflection in ConfigureHowToFindSaga was not going to work anyway. There would be no way to parse the IL instructions of that reflection code to determine what your CorrelationId is at compile time.

Take a look at the [new API in NServiceBus 7.4](https://particular.net/blog/whats-new-nservicebus-7-4#finding-sagas) for mapping sagas, it takes out a lot of the duplication:

```
public override void ConfigureMapping(SagaPropertyMapper<MySagaData> mapper)
{
  mapper.MapSaga(saga => saga.CustomerId)
    .ToMessage<OrderShipped>(msg => msg.CustomerId)
    .ToMessage<OrderBilled>(msg => msg.CustomerId);
}
```

As far as wrapped methods to include logging logic when sending or publishing, these are better handled by [pipeline behaviors](https://docs.particular.net/nservicebus/pipeline/manipulate-with-behaviors) which are generally preferred for cross-cutting concerns like logging.

I didn't test this, just whipped it up with Intellisense, but a behavior similar to this would probably provide that functionality:

```
public class LogOnOutgoingMessageBehavior : Behavior<IOutgoingLogicalMessageContext>
{
    public override Task Invoke(IOutgoingLogicalMessageContext context, Func<Task> next)
    {
        var operationType = context.Headers[Headers.MessageIntent];
        var messageId = context.MessageId;
        var messageType = context.Message.MessageType;

        logger.Info($"{operationType}ing message {messageId} of type {messageType}");        
        return next();
    }
    
    static ILog logger = LogManager.GetLogger<LogOnOutgoingMessageBehavior>();
}
```

**Comment by ajepst** [comment]
@DavidBoike I'm working on upgrading an older project to use Sql Server for persistence instead of Raven (project uses NSB6).  Unfortunately, the scenario I'm dealing with is almost identical to the scenario described in this issue - the project I'm dealing with makes extensive use of abstract base classes and has a large number of sagas, so reworking the solution to eliminate the base classes is looking to be a large task. Is there any sort of workaround/bridge to allow me to generate the Saga scripts as-is? Long term, it's clear that Pipelines, Features, etc can be used to replace functionality in the base classes and it's also clear that doing so is Particular's recommendation going forward, but this is a fairly large, surprise blocker that feels unrelated to getting off Raven.

**Comment by DavidBoike** [comment]
Hey @ajepst!

You could just [disable script generation completely](https://docs.particular.net/persistence/sql/controlling-script-generation#disabling-script-generation). Then, either don't enable installers at all (i.e. [don't do this](https://docs.particular.net/nservicebus/operations/installers#running-installers)) or [just disable persistence installers](https://docs.particular.net/persistence/sql/install#script-execution-in-non-development-environments).

Or leave installers enabled, but fake them out by putting the files in your project and marking them as content that will get copied to the output directory.

The Timeout/Outbox/Subscription scripts are all the same everywhere, and even the saga scripts aren't THAT different. The [script for a saga in SqlServer is here](https://docs.particular.net/persistence/sql/sqlserver-scripts#build-time-saga-create-table). The things that are dynamically generated are:

* The name and type of the correlation id property. If you have a base class, then this is probably always something like `string CorrId` anyway so the saga script would be the same between multiple sagas.
* The index on the correlation property column, based on the name.
* If there is a [transitional correlation id](https://docs.particular.net/samples/sql-persistence/transitioning-correlation-ids/) (which not many people use, and if you are just converting from Raven, you won't need) there's a second `Correlation_*` column and another index on that column.

Honestly, I kind of wish that back in the day we had just said "The correlation id must be a string (a good idea anyway) and the column name will always be CorrelationValue" and then every single Saga table would be the same (except for the table name) and we wouldn't need to scan anything.

Does that help?

**Comment by ajepst** [comment]
Thanks for the quick response, @DavidBoike, and thanks for the suggestion. 

Manually creating the saga scripts isn't ideal either for the number of sagas I'm dealing with, but with the saga scripts being 90% the same, it's probably the best option to get us unblocked for now. Manual script creation is going to be a lot faster, more straightforward, and far lower risk than trying to unwind the complexities around the base classes in this application right now.
