### ISSUE TITLE
Abstract saga data

### ISSUE THREAD

**Issue by StefanoVuerich** [Particular/NServiceBus.Persistence.Sql#831]
Good morning,

I'm trying to use abstract saga data like this, I would like all my saga data classes to have a correlation id :

```C#
public abstract class AbstractSagaData : ContainSagaData
{
        public Guid CorrelationId { get; set; }
}

public class MySagaData : AbstractSagaData 
{
        //public Guid CorrelationId { get; set; } correlation id column is generated only if property is specified in concrete class
}

public class MySaga : Saga<MySagaData> 
{
       //implementation here
}
```

The sql generated script add correlation id only if correlation id property is on the concrete class.

**Comment by DavidBoike** [comment]
Similar to #830, this is because of the compile-time generation that is going on, where much less is known about the type hierarchies. The generator needs to know that the correlation property exists on the saga data class and that it is not read-only.

This is also kind of a "pit of success" check, as sagas are supposed to function similar to a DDD aggregate root, and shouldn't have unnecessary coupling to other things, including base classes, which would make things harder to change.

**Comment by StefanoVuerich** [comment]
Ok, but that means that for every saga data I will use I have to repeat correlation id property, breaking DRY principle.

I think you should provide a correlation id property by default, maybe on the ContainSagaData class as "The saga Id available via IContainSagaData or ContainSagaData is considered internal to NServiceBus and must not be used to correlate messages. Instead, add an additional property that contains a unique saga instance identifier."

Message correlation is needed when we talking about saga so I think this is not "unnecessary coupling".

Best Regards.

**Comment by DavidBoike** [comment]
>  that means that for every saga data I will use I have to repeat correlation id property

That is true, however most customers do not use a generic CorrelationId property (or similar) and instead use something to convey meaning of what the data contains, such as OrderId, CustomerId, or whatever makes sense for each individual saga.
