### ISSUE TITLE
Why this over NHibernate?

### ISSUE THREAD

**Issue by markgould** [Particular/NServiceBus.Persistence.Sql#88]
Is there a document / write up about why one might want to use this over the NHibernate persistence? I like the idea of this as I'm not using NHibernate for anything else. It would be nice to see a pro/con list of why you should choose one over the other.

**Comment by DavidBoike** [comment]
Hey @markgould, good question. I'll provide what I can at a very high level.

* One less dependency is good, especially considering many aren't using NHibernate for anything else.
* With NHibernate we only supported SQL Server and Oracle. With SQL Persistence we already support SQL Server, MySQL, and Oracle, and as soon as MariaDB and Amazon Aurora support the JSON column type, we should be able to support those too. We've also got planned support for Postgres sometime in the future.
* Schema creation scripts are created at compile time, rather than at runtime, and can be promoted from the bin directory to a source directory and be included in source control. A DBA can examine those scripts and run them with elevated privileges which the endpoint doesn't need to have, and you can easily see any changes if you have them checked into source control.
* No ORM magic, which DBAs tend to like, and you can view all the schema and queries for [SQL Server](https://docs.particular.net/nservicebus/sql-persistence/sqlserver-scripts), [MySQL](https://docs.particular.net/nservicebus/sql-persistence/mysql-scripts), and [Oracle](https://docs.particular.net/nservicebus/sql-persistence/oracle-scripts) right on our docs site.
* Each endpoint gets its own table for subscriptions, timeouts, and outbox. Especially for timeouts and outbox, where there is a lot of churn, this is good because a busy endpoint won't be able to generate locks that affect any other endpoint.
* Saga data is serialized in a document database fashion (JSON blob in the table) so small changes to saga data won't require schema changes.
* Each persistence type supports a persistence version column, so you'll know exactly which version of the persister created each row in the database. In the future if we have bugs we can fix it and have mitigations based on specific versions rather than trying to infer based on what the data looks like.
* Sagas also contain the version of the assembly containing the saga, allowing you to make the same sorts of judgments as you evolve and maintain sagas over the long term.
* Sagas have a concept of a transitional correlation id, allowing you to change the correlation id of a long running saga gradually over time.
* We're not certain about the future of NHibernate. At the very least, it currently does not support async/await.
* NHibernate's LGPL license is a blocker for some.

I may have missed something. :wink:

**Comment by MarcinHoppe** [comment]
One thing is that it also opens a way for .NET Standard support, which (as far as we know) is not likely to happen with NHibernate.

**Comment by SzymonPobiega** [comment]
Should we add a comparison page similar to this one https://docs.particular.net/nservicebus/msmq/scaling-out ?

**Comment by markgould** [comment]
This is perfect and confirms a lot of what I suspected. I'm starting to use it in a project and so far it's working great.

I like the table format now, I much prefer having the underscores instead of the periods, but it looks a little odd now when using SQL Persistence and SQL Transport together. SQL Transport creates tables like schema.EndpointName.Timeouts and this creates them as schema.EndpointName_TimeoutData. 

It would be nice if they were consistent (Ideally SQL Transport changing but I understand that could be a major change and a pain point to deal with)

**Comment by SzymonPobiega** [comment]
@markgould I've raised an issue for the SQL transport: https://github.com/Particular/NServiceBus.SqlServer/issues/361

**Comment by DavidBoike** [comment]
I think this issue can probably be closed. @markgould thanks for the question! Please feel free to reopen if I've missed anything.
