### ISSUE TITLE
Implement pessimistic saga concurrency

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus.Persistence.Sql#98]
The current implementation relies on optimistic concurrency which guarantees the correctness of saga processing and is OK in low-congestion scenarios.

For high-congestion scenarios where high number of messages is meant to be processed by a single saga instance the optimistic concurrency is not efficient enough.

### PoA

 * [ ] Add information to the NHibernate -> SQL migration guide that SQL is not (yet) ready for high-congestion workloads
 * [ ] Implement proper pessimistic locking for all supported database dialects.

**Comment by SimonCropp** [comment]
@SzymonPobiega we are bumping into this. any update?

**Comment by SzymonPobiega** [comment]
@SimonCropp I think it was stuck here for a while. I'll make sure to try to pitch this idea this week.

**Comment by mariusin79** [comment]
Just to add to your sales pitch: Serial saga access is also great when working against 3rd party APIs which do not support idempotency.

**Comment by dvdstelt** [comment]
@mariusin79 This isn't really something that we could ever solve. But one step in the right direction would be to extract that action from the saga and move it into a separate handler. Less likely for the message to be retried if its only concern is to contact the 3rd party API.

Having said that, we advise you to always do this and only do orchestration of a process inside a saga. Everything else, everything, should be delegated to different handlers, in most cases.
https://docs.particular.net/nservicebus/sagas/#accessing-databases-and-other-resources-from-a-saga

**Comment by mariusin79** [comment]
I usually follow that pattern (separate handlers), but I am bit confused as to the "this is something we can't solve". Pessimistic locking will only allow one thread at a time access to the saga?

**Comment by dvdstelt** [comment]
> Pessimistic locking will only allow one thread at a time access to the saga?

Most definitely! I was referring to the fact that we can't solve idempotence on the side of the 3rd party. Imagine an SMTP server which is not transactional. If we successfully send an email to the SMTP server, but the message still fails, due to whatever reason, it's very likely we'll send the email again. I should've stated clearer what it was that we cannot solve.

But separate handlers is definitely the way to go. Pessimistic locking on saga state should help better with high contention on a single saga, than optimistic locking would.

**Comment by SzymonPobiega** [comment]
Closed via https://github.com/Particular/NServiceBus.Persistence.Sql/pull/286
